Feature/gd 166 add xml documentation
IT-Siberians/LotsArchiveMicroservice pull request #2
Opened 2024-08-20 11:08 UTC by m-a-ilnitsky

GD-64 Created solution. Added domain entities, value objects, exceptions
GD-64 Renamed solution
GD-64 Added explicit using, and small fixes
GD-145 Added in-memory repository
GD-155 Added EF repository
GD-164 Simplified the properties of entities
GD-166 Added xml-documentation to domain and common classes

2024-08-20 11:49 UTC, Barmalej24 approved these changes
Код понравился. Есть вопрос по реализации удаления сущностей в репозиториях, почему жестко удаляем данные, а не используем "мягкое" удаление через дополнительно поле допустим IsRemove

2024-08-23 05:32 UTC, NikeTorchwood approved these changes
всё гуд, присутствует в навигационных свойствах обращение через стрингу, я бы вынес бы это в константу или бы изменял бы слой домейн

2024-08-23 09:22 UTC, oleggolen commented on src/Common/Auction.Common.Domain/RepositoriesAbstractions/IRepository.cs
> +    where TKey : notnull, IEquatable<TKey>
Лучше здесь использовать ограничение по типу stuct или вобще, что ключ является примитивным типом для корректной работы с БД

2024-08-23 09:22 UTC, oleggolen commented on src/Common/Auction.Common.Domain/RepositoriesAbstractions/IRepository.cs
> +    Task AddAsync(TEntity entity);
Лучше отсюда что-нибудь вернуть, так как клиентскому коду скорее всего понадобится хотя бы Id только добавленной сущности

2024-08-23 09:24 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +    }
Я бы ещё добавил перегрузки операторов равенства/неравенства

2024-08-23 09:25 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +        if (validator == null) throw new ArgumentNullValueException(nameof(validator));
Думаю, что вряд ли возможная ситуация, так как валидаторы мы подставляем из классов-наследников, и там вряд ли возможно кинуть null, а даже, если и кинем, то сразу будет понятно в чём дело

2024-08-23 09:25 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +        if (value == null) throw new ArgumentNullValueException(nameof(value));
Здесь бы я использовал какое-нибудь более конкретное доменное исключение

2024-08-23 09:27 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Money.cs
> +            if (value < 0) throw new MoneyValueException(value);
Если money decimal, то это вещественное число, чисто в теории тогда можно поставить 0,000001 копейки, и как это трактовать?

2024-08-23 10:11 UTC, oleggolen requested changes
В целом очень хороший код, реализованы основная логика и проверки, очень хорошо реализованы репозитории, сделана иерархия исключений, есть проверки на всё и на вся. Стоит убрать излишнюю иерархию собственных исключений, и использовать частично уже готовые системные исключения, которые максммально подходят к конкретной исключительной ситуации,также убрать лишние абстрактные классы иерархии, которые несут мало смысла, и быть более внимательным в проверке типа "Деньги.". Очень надеюсь, что полученные комментарии помогут писать легко читаемый и понятный код, реализовывать домены почти для любой задачи

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/ArgumentNullValueException.cs
> +        $"Argument \"{argumentName}\" value is null");
Как будто бы лучше тут использовать системный класс исключения ArgumentNullException, в отличии от не совсем очевидной иерархии доменных исключений

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/IEntity.cs
> +    where TKey : notnull, IEquatable<TKey>
Использовать проверку на примитивный тип для ключа для корректной работы базы данных

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/IEntity.cs
> +public interface IEntity<TKey>
Добавить модификатор out

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +    where TKey : notnull, IEquatable<TKey>
Добавить проверку на примитивный тип для ключа для корректной работы базы данных

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +        Username = username ?? throw new ArgumentNullValueException(nameof(username));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +        Username = username ?? throw new ArgumentNullValueException(nameof(username));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullExceptuin

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractLot.cs
> +    where TKey : notnull, IEquatable<TKey>
Выполнить проверку на примитивный тип для корректной работы базы данных

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractLot.cs
> +        Title = title ?? throw new ArgumentNullValueException(nameof(title));
Лучше использовать более кокретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractLot.cs
> +        Description = description ?? throw new ArgumentNullValueException(nameof(description));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainException.cs
> +public class DomainException(string message) : Exception(message);
Вообще непонятное исключение, по сути дела ничем не отличаюшиеся от просто иключения, хотя бы его abstract тогда можно было бы сделать, но лучше просто убрать

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +public abstract class AbstractInMemoryRepository<TEntity, TKey>
Не понятно зачем класс абстрактный, если ничего абстрактного он в себе не содержит

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    where TKey : notnull, IEquatable<TKey>
Проверить на примитивный тип

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +            ?? throw new ArgumentNullValueException(nameof(entities));
Здесь можно кинуть просто ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    protected AbstractInMemoryRepository(IEnumerable<TEntity> entities)
Сделать primary конструктор

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    }
Для чего нужен этот метод?

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext = dbContext ?? throw new ArgumentNullValueException(nameof(dbContext));
Лучшпе использовать просто ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Infrastructure/Auction.LotsArchiveMicroservice.Infrastructure.RepositoriesImplementations/Ef/EfRepository.cs
> +public class EfRepository<TEntity>(ApplicationDbContext dbContext)
Не понятен смысл этого класса вообще, если есть точно такой же неабстрактный класс

2024-08-23 10:11 UTC, oleggolen commented on src/Infrastructure/Auction.LotsArchiveMicroservice.Infrastructure.RepositoriesImplementations/InMemory/InMemoryRepository.cs
> +    where TEntity : class, IEntity<Guid>;
Непонятен смысл этого класса, как такового

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/WithdrawnLot.cs
> +        Lot = lot ?? throw new ArgumentNullValueException(nameof(lot));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/WithdrawnLot.cs
> +    public WithdrawnLot(Guid id, DateTime date, Lot lot)
Использовать primary конструктор

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/WithdrawnLot.cs
> +        Lot = lot ?? throw new ArgumentNullValueException(nameof(lot));
Использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Seller.cs
> +        _unpurchasedLots = unpurchasedLots ?? throw new ArgumentNullValueException(nameof(unpurchasedLots));
Использовать более конкретные доменные исключения, наследованные от ArgumentNullExceptuin

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Seller.cs
> +        ?? throw new FieldNullValueException(nameof(_unpurchasedLots));
Либо использовать более кокретные доменные исключения, либо просто возвращать пустые коллекции в случае null, но скорее всего ситуация, когда тут будет null просто невозможна, так как эта проверка есть в конструкторе, и объект просто не создастя, либо это значение положит EF, через рефлекцию, и очень мало вероятно, что он будет класть null, а не пустую коллекцию

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/RepurchasedLot.cs
> +        EndPrice = endPrice ?? throw new ArgumentNullValueException(nameof(endPrice));
Использовать более конкретные доменные исключения, наследованные от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/RepurchasedLot.cs
> +    public RepurchasedLot(
Использовать primary конструктор

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Lot.cs
> +        PriceStep = priceStep ?? throw new ArgumentNullValueException(nameof(priceStep));
Использовать более конкретные доменные исключения, насдеованные от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Lot.cs
> +    public Lot(
Использовать primary конструктор

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Buyer.cs
> +        _boughtLots = boughtLots ?? throw new ArgumentNullValueException(nameof(boughtLots));
Использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 10:11 UTC, oleggolen commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Buyer.cs
> +        ?? throw new FieldNullValueException(nameof(_boughtLots));
Использовать либо более конкретное доменное исключение, либо возвращать пустую коллекцию, либо вообще убрать проверку, так как вероятность null равна практически нулю, потому что есть проверка в конструкторе, и EF вряд ли будет класть null сюда, в случае если не найдет элементы, он скорее всего положит пустую коллекцию, соответственно такой код никогда не сработает

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainStateException.cs
> +public class DomainStateException(string message) : DomainException(message);
Не очень понятен смысл этого исключения, оно максимально не конкретно

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainValidationException.cs
> +public class DomainValidationException(string message) : DomainException(message);
Не понятен смысл этого исключения, оно максимально не конкретно, либо стоит наследовать от чего-то более конкретного из системых исключений и сделать абстрактным, либо убрать вообще

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/TextNullValueException.cs
> +    : DomainValidationException("Text cannot be null");
Лучше сдесь наследование от какого-нибудь ArgumentNullException или от FormatException и принимать какие-то параметры, в таком виде это исключение максимально не конкретно и не понятен его смысл

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/TextEmptyValueException.cs
> +        $"The text cannot be an empty string or a space, the passed value is \"{value}\"");
Лучше сдесь наследование от какого-нибудь ArgumentNullException или от FormatException и принимать какие-то параметры, в таком виде это исключение максимально не конкретно и не понятен его смысл

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameNullValueException.cs
> +    : DomainValidationException("Name cannot be null");
Лучше принять какой-нибудь дополнительный параметр, который скажет какое именно имя, а также наследовать например от ArgumentyNullException или FormatException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameLongValueException.cs
> +        $"The line must be no longer than {maxLength} characters, the passed value is \"{value}\"");
Лучше принять какой-нибудь дополнительный параметр, который скажет какое именно имя, а также наследовать например от ArgumentyNullException или FormatException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameEmptyValueException.cs
> +        $"The name cannot be an empty string or a space, the passed value is \"{value}\"");
Лучше принять какой-нибудь дополнительный параметр, который скажет какое именно имя, а также наследовать например от ArgumentyNullException или FormatException

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/MoneyValueException.cs
> +        $"The money value cannot be less than 0, the passed value is: {value}");
В целом пойдёт, но лучше переименовать в что-то типо MoneyNegativeValueException, наследовать от FormatException, и добавить конкретики откуда такое взялось

2024-08-23 10:11 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/FieldNullValueException.cs
> +        $"Field \"{fieldName}\" value is null");
Максимально непонятное и неконкретное исключение, стоит добавить больше деталей, где как и откуда, а также наследовать его, например от FormatException

2024-08-26 09:55 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +        Username = username ?? throw new ArgumentNullValueException(nameof(username));
Не понял замечание, это и так конкретное доменное исключение, это не само ArgumentNullException.
Здесь нет смысла бросать исключение NameNullValueException для валуэ-обджекта Name, т.к. здесь не создается Name, а только передается в качестве аргумента готовый объект Name - это разные ситуации, поэтому нелогично бросать бросать для них одинаковые исключения

2024-08-26 10:00 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    }
Для валидации - проверки на null

2024-08-26 10:02 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    protected AbstractInMemoryRepository(IEnumerable<TEntity> entities)
Не понял, для чего?
Или речь о варианте когда этот класс будет неабстрактным?

2024-08-26 10:07 UTC, m-a-ilnitsky commented on src/Domain/Auction.LotsArchiveMicroservice.Domain/Entities/Buyer.cs
> +        ?? throw new FieldNullValueException(nameof(_boughtLots));
Наличие такого исключения предотвращает варнинги при использовании nullable-контекста.
Иначе статический анализатор будет предлагать заменить возвращаемый тип с IReadOnlyCollection<RepurchasedLot> на IReadOnlyCollection<RepurchasedLot>?

2024-09-05 10:12 UTC, closed without merging