GD-181 Added UnitOfWork
IT-Siberians/LotsArchiveMicroservice pull request #3
Opened 2024-09-03 01:53 UTC by m-a-ilnitsky

Добавлен UnitOfWork в микросервис Архива.
Эти изменения уникальны для микросервиса Архива.

2024-09-03 10:55 UTC, Barmalej24 approved these changes

2024-09-04 11:15 UTC, NikeTorchwood commented on src/Infrastructure/Auction.LotsArchiveMicroservice.Infrastructure.RepositoriesImplementations/EntityFramework/EfUnitOfWork.cs
> +        Sellers = new BaseEfRepositoryWithUpdateAndDelete<ApplicationDbContext, Seller, Guid>(_dbContext);
много new ...  возможно стоит подумать как делегировать это DI

2024-09-04 11:17 UTC, NikeTorchwood commented on src/Infrastructure/Auction.LotsArchiveMicroservice.Infrastructure.RepositoriesImplementations/EntityFramework/EfUnitOfWork.cs
> +        Sellers = new BaseEfRepositoryWithUpdateAndDelete<ApplicationDbContext, Seller, Guid>(_dbContext);
даже так свойства - это интерфейсы, но при этом ты зачем то сам их создаешь. это же по сути просто регистрируется в контейнере.

2024-09-04 11:19 UTC, NikeTorchwood requested changes
отличное решение объединить всё в один UnitOfWork, и понимаю что слой Presentation еще не сделан, но думаю что нарушаются принципы солид поэтому на доработку

2024-09-18 07:20 UTC, oleggolen requested changes
Вообще не понимаю идею этого всего

2024-09-18 07:21 UTC, closed without merging

2024-09-18 11:06 UTC, m-a-ilnitsky commented
> Вообще не понимаю идею этого всего

Не понимаю, что именно вам не нравится

2024-09-27 13:09 UTC, m-a-ilnitsky commented
https://learn.microsoft.com/ru-ru/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application

![image](https://github.com/user-attachments/assets/06114321-fff1-4f5a-99be-ff9995702042)